version: '3'

services:
  php-fpm:
    build:
      context: ./
      dockerfile: ./php-fpm/Dockerfile
  nginx:
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
    depends_on:
      - php-fpm
    ports:
      # port_yang_bisa_diakses_dari_luar:internal_docker
      - "17100:4000"
